# A Simple Neural Network Making a Prediction

### What is a Neural Network?

In [5]:
# The network:

weight = 0.1 
neural_network(input, weight) = input * weight

# How we use the network to predict something:

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[1]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001

# Making a Prediction with Multiple Inputs

### Complete Runnable Code

In [213]:
function w_sum(a,b)
    @assert length(a) == length(b)
    output = 0
    for i in 1:length(a)
        output += (a[i] * b[i])
    end
    return output
end

weights = [0.1 0.2 0] 
    
function neural_network(input, weights)
    w_sum(input, weights)
end

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season.

# toes = current number of toes
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes =  [8.5 9.5 9.9 9.0]
wlrec = [0.65 0.8 0.8 0.9]
nfans = [1.2 1.3 0.5 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[1] wlrec[1] nfans[1]]
pred = neural_network(input, weights)

print(pred)

0.9800000000000001

### Julia LinearAlgebra

In [136]:
using LinearAlgebra

weights = [0.1 0.2 0]
neural_network(input, weights) = dot(input, weights)
    
toes =  [8.5 9.5 9.9 9.0]
wlrec = [0.65 0.8 0.8 0.9]
nfans = [1.2 1.3 0.5 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[1] wlrec[1] nfans[1]]
pred = neural_network(input, weights)

print(pred)

0.9800000000000001

# Making a Prediction with Multiple Outputs

In [214]:
# Instead of predicting just 
# whether the team won or lost, 
# now we're also predicting whether
# they are happy/sad AND the percentage
# of the team that is hurt. We are
# making this prediction using only
# the current win/loss record.

function ele_mul(number, vector)
    output = [.0, .0, .0]
    @assert (length(output) == length(vector))
    for i in 1:length(vector)
        output[i] = number * vector[i]
    end
    return output
end

weights = [0.3 0.2 0.9] 

neural_network(input, weights) = ele_mul(input, weights)
    
wlrec = [0.65 0.8 0.8 0.9]
input = wlrec[1]
pred = neural_network(input,weights)

print(pred)

[0.195, 0.13, 0.585]

# Predicting with Multiple Inputs & Outputs

In [47]:
            #toes #win #fans
weights = [ [0.1 0.1 -0.3], #hurt?
            [0.1 0.2 0.0], #win?
            [0.0 1.3 0.1], ] #sad?

function w_sum(a, b)
    @assert length(a) == length(b)
    output = 0
    for i in 1:length(a)
        output += (a[i] * b[i])
    end
    return output
end

function vect_mat_mul(vect, matrix)
    @assert length(vect) == length(matrix)
    output = [.0 .0 .0]
    for i in range(1, stop=length(vect))
        output[i] = w_sum(vect, matrix[i])
    end
    return output
end

neural_network(input, weights) = vect_mat_mul(input,weights)

# This dataset is the current
# status at the beginning of
# each game for the first 4 games
# in a season.

# toes = current number of toes
# wlrec = current games won (percent)
# nfans = fan count (in millions)

toes =  [8.5 9.5 9.9 9.0]
wlrec = [0.65 0.8 0.8 0.9]
nfans = [1.2 1.3 0.5 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[1] wlrec[1] nfans[1]]
pred = neural_network(input, weights)

print(pred)

[0.555 0.98 0.965]

# Predicting on Predictions

In [49]:
            #toes #win #fans
ih_wgt = [ [0.1, 0.2, -0.1], #hid[0]
           [-0.1, 0.1, 0.9], #hid[1]
           [0.1, 0.4, 0.1] ] #hid[2]

           #hid[0] hid[1] hid[2]
hp_wgt = [ [0.3, 1.1, -0.3], #hurt?
           [0.1, 0.2, 0.0], #win?
           [0.0, 1.3, 0.1] ] #sad?

weights = [ih_wgt, hp_wgt]

function neural_network(input, weights)
    hid = vect_mat_mul(input, weights[1])
    pred = vect_mat_mul(hid, weights[2])
    return pred
end

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Input corresponds to every entry
# for the first game of the season.

input = [toes[1], wlrec[1], nfans[1]]
pred = neural_network(input, weights)

print(pred)

[0.2135 0.145 0.5065]

# Julia LinearAlgebra

In [75]:
using LinearAlgebra

           #toes #win #fans
ih_wgt = [ 0.1 0.2 -0.1; #hid[0]
           -0.1 0.1 0.9; #hid[1]
           0.1 0.4 0.1 ] #hid[2]

           #hid[0] hid[1] hid[2]
hp_wgt = [ 0.3 1.1 -0.3; #hurt?
           0.1 0.2 0.0; #win?
           0.0 1.3 0.1 ] #sad?

weights = [ih_wgt, hp_wgt]

function neural_network(input, weights)
    hid = [dot(input, row) for row in eachrow(weights[1])]
    pred = [dot(hid, row) for row in eachrow(weights[2])]
    return pred
end

toes =  [8.5 9.5 9.9 9.0]
wlrec = [0.65 0.8 0.8 0.9]
nfans = [1.2 1.3 0.5 1.0]

input = [toes[1] wlrec[1] nfans[1]]

pred = neural_network(input, weights)

print(pred)

[0.2135, 0.145, 0.5065]

# A Quick Primer on Julia

In [76]:
a = [0 1 2 3] # a vector
b = [4 5 6 7] # another vector
c = [0 1 2 3; 4 5 6 7] # a matrix

d = zeros(2, 4) # (2x4 matrix of zeros)
e = rand(2, 5) # random 2x5
# matrix with all numbers between 0 and 1

println(a)
println(b)
println(c)
println(d)
println(e)

[0 1 2 3]
[4 5 6 7]
[0 1 2 3; 4 5 6 7]
[0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0]
[0.788067 0.392528 0.0366427 0.329013 0.731914; 0.361262 0.0364661 0.942432 0.163024 0.548304]


In [77]:
println(a * 0.1) # multiplies every number in vector "a" by 0.1
      
println(c * 0.2) # multiplies every number in matrix "c" by 0.2
      
println(a .* b) # multiplies elementwise between a and b (columns paired up)
      
println(a .* b * 0.2) # elementwise multiplication then multiplied by 0.2
      
println(a .* c) # since c has the same number of columns as a, this performs
# elementwise multiplication on every row of the matrix "c"

println(a * e) # since a and e don't have the same number of columns, this
# throws "DimensionMismatch: ("matrix A has dimensions (1,4), matrix B has dimensions (1,4)")"

[0.0 0.1 0.2 0.3]
[0.0 0.2 0.4 0.6; 0.8 1.0 1.2 1.4]
[0 5 12 21]
[0.0 1.0 2.4 4.2]
[0 1 4 9; 0 5 12 21]


DimensionMismatch: DimensionMismatch("matrix A has dimensions (1,4), matrix B has dimensions (2,5)")

In [64]:
using LinearAlgebra

a = zeros(1, 4) # vector of length 4
b = zeros(4, 3) # matrix with 4 rows & 3 columns

c = a * b

print(size(c))

(1, 3)

In [79]:
a = zeros(2, 4) # matrix with 2 rows and 4 columns
b = zeros(4, 3) # matrix with 4 rows & 3 columns

c = a * b
println(size(c)) # outputs (2,3)

e = zeros(2, 1) # matrix with 2 rows and 1 columns
f = zeros(1, 3) # matrix with 1 row & 3 columns

g = e * f
println(size(g)) # outputs (2,3)

h = zeros(5, 4)' # matrix with 4 rows and 5 columns
i = zeros(5 ,6) # matrix with 6 rows & 5 columns

j = h * i
println(size(j)) # outputs (4,6)

h = zeros(5, 4) # matrix with 5 rows and 4 columns
i = zeros(5, 6) # matrix with 5 rows & 6 columns
j = h * i
println(size(j)) # throws an error

(2, 3)
(2, 3)
(4, 6)


DimensionMismatch: DimensionMismatch("A has dimensions (5,4) but B has dimensions (5,6)")